# Generated by Django 4.2.7 on 2025-08-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaceCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculator_type",
                    models.CharField(
                        choices=[
                            ("daniels_vdot", "Daniels VDOT"),
                            ("mcmillan", "McMillan"),
                            ("riegel", "Riegel Formula"),
                            ("cameron", "Cameron Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("race_distance", models.CharField(max_length=20)),
                ("race_time_seconds", models.IntegerField()),
                ("calculated_vdot", models.FloatField()),
                ("easy_pace", models.CharField(max_length=10)),
                ("marathon_pace", models.CharField(max_length=10)),
                ("threshold_pace", models.CharField(max_length=10)),
                ("interval_pace", models.CharField(max_length=10)),
                ("repetition_pace", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
