# Generated by Django 4.2.7 on 2025-08-07 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumTrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "distance",
                    models.CharField(
                        choices=[
                            ("5k", "5K"),
                            ("10k", "10K"),
                            ("15k", "15K"),
                            ("half_marathon", "Half Marathon"),
                            ("marathon", "Marathon"),
                            ("ultra", "Ultra Marathon"),
                            ("multi", "Multi-Distance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("elite", "Elite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("base", "Base Building"),
                            ("build", "Build Phase"),
                            ("peak", "Peak/Sharpening"),
                            ("full_cycle", "Full Training Cycle"),
                            ("specialty", "Specialty Program"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(help_text="Plan duration in weeks"),
                ),
                (
                    "weekly_mileage_range",
                    models.CharField(
                        help_text="e.g., '40-60 miles/week'", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed plan description"),
                ),
                (
                    "key_features",
                    models.TextField(
                        help_text="Bullet points of key features (one per line)"
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(help_text="Who this plan is designed for"),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True, help_text="Required fitness level or experience"
                    ),
                ),
                (
                    "training_philosophy",
                    models.TextField(help_text="The approach and methodology"),
                ),
                (
                    "sample_week",
                    models.TextField(help_text="Example training week structure"),
                ),
                (
                    "workout_types",
                    models.TextField(help_text="Types of workouts included"),
                ),
                (
                    "progression_strategy",
                    models.TextField(help_text="How the plan builds over time"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional sale price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_on_sale", models.BooleanField(default=False)),
                (
                    "pdf_url",
                    models.URLField(blank=True, help_text="Link to downloadable PDF"),
                ),
                (
                    "spreadsheet_url",
                    models.URLField(
                        blank=True, help_text="Link to training log spreadsheet"
                    ),
                ),
                (
                    "bonus_content",
                    models.TextField(
                        blank=True, help_text="Additional bonus materials included"
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("keywords", models.CharField(blank=True, max_length=200)),
                ("featured_image", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_location", models.CharField(blank=True, max_length=100)),
                ("testimonial", models.TextField()),
                (
                    "race_result",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Boston Marathon: 3:15:42'",
                        max_length=200,
                    ),
                ),
                (
                    "improvement",
                    models.CharField(
                        blank=True, help_text="e.g., '15-minute PR'", max_length=200
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="premium.premiumtrainingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="categories",
                        to="premium.premiumtrainingplan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Plan Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchasedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("payment_id", models.CharField(blank=True, max_length=100)),
                (
                    "payment_status",
                    models.CharField(default="completed", max_length=50),
                ),
                ("access_granted", models.BooleanField(default=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="premium.premiumtrainingplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
                "unique_together": {("user", "plan")},
            },
        ),
        migrations.AddIndex(
            model_name="premiumtrainingplan",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="premium_pre_is_acti_f8a4c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="premiumtrainingplan",
            index=models.Index(
                fields=["distance", "difficulty"], name="premium_pre_distanc_563682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="premiumtrainingplan",
            index=models.Index(
                fields=["plan_type", "is_active"], name="premium_pre_plan_ty_27d039_idx"
            ),
        ),
    ]
