# Generated by Django 4.2.7 on 2025-08-04 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("5k", "5K Training"),
                            ("10k", "10K Training"),
                            ("half_marathon", "Half Marathon Training"),
                            ("marathon", "Marathon Training"),
                            ("custom", "Custom Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.IntegerField()),
                ("target_vdot", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("day", models.IntegerField()),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("easy", "Easy Run"),
                            ("marathon", "Marathon Pace"),
                            ("threshold", "Threshold/Tempo"),
                            ("interval", "Interval Training"),
                            ("repetition", "Repetition"),
                            ("long", "Long Run"),
                            ("recovery", "Recovery Run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("distance", models.FloatField()),
                ("target_pace", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "training_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.trainingplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.CharField(
                        choices=[
                            ("5K", "5K"),
                            ("10K", "10K"),
                            ("15K", "15K"),
                            ("half_marathon", "Half Marathon"),
                            ("marathon", "Marathon"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_distance", models.FloatField(blank=True, null=True)),
                ("time_seconds", models.IntegerField()),
                ("race_date", models.DateField()),
                ("race_name", models.CharField(blank=True, max_length=200)),
                ("elevation_gain", models.IntegerField(blank=True, null=True)),
                ("temperature", models.IntegerField(blank=True, null=True)),
                ("humidity", models.IntegerField(blank=True, null=True)),
                ("calculated_vdot", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
